version: '3.2'

services:
  python:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - chrome
    volumes:
      - type: volume
        source: html
        target: /html


  chrome:
    image: selenium/standalone-chrome
    healthcheck:
      test: wget -qO - http://chrome:4444/wd/hub || exit 1
      interval: 3s
      timeout: 3s
      retries: 2

volumes:
  html: