version: '3.2'

services:
  python:
    volumes:
      - type: bind
        source: /home/alec/scraped-data
        target: /scraped-data

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5900:5900"
